sonar.projectKey=commander
sonar.sources=src,tests
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**, **/*.md
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest_report.xml