# This is the default configuration for new connections to the system.
# This file is not used directly for any connections, only as a template for new configurations 
# that are added to config.local.yaml via config.py

# The host and port have placeholder values in this file that will be replaced when adding a new connection.
socket_host: "default_host"
socket_port: 8080

acceptable_box_percent: 0.4 # Percentage of the frame width and height used to define the size of the acceptable box
vertical_field_of_view: 48 # vertical FOV of camera being used
horizontal_field_of_view: 89 # horizontal FOV of camera being used
confirmation_delay: 0.25 # Amount of time subject is outside of acceptable box before a command is sent
camera_index: 0 # Index of the camera device to be used for video capture
# Link to camera feed to be used for video capture
# camera_index: http://unctalos.student.rit.edu:5000/video_feed

command_delay: 0.25 # Wait time before another command can be sent
fps: 30 # Frame rate to update the gui video
frame_width: 500 # Desired width of the video frame
# frame_height: 600 # auto calculate if commented out
