socket_host: operator.talos
socket_port: 61616
acceptable_box_percent: 0.4
vertical_field_of_view: 48
horizontal_field_of_view: 89
confirmation_delay: 0.25
camera_index: 0
command_delay: 0.25
fps: 30
frame_width: 500
